import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import ToastProvider from "@/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
